Script to analyze MC data using the FBK SiPMs applying saturation.
petalo-project/ANTEA pull request #21
Opened 2023-11-27 07:06 UTC by NereaSalor

This PR includes a script to analyze the MC data obtained with the geometry used with the FBK SiPMs taking into account the sensors saturation. The most relevant functions included in the script are for joining the sensors in groups of 4 and to apply SiPM saturation. It also includes a test and a data file to run the test.

2023-11-27 22:59 UTC, paolafer requested changes

2023-11-27 22:59 UTC, paolafer commented on antea/scripts/process_mc_petit_FBK.py
> +            if n < 390: # To change the TOFPET plane
It seems to me that the same thing happens if `n < 390` or if `n >= 390`, right? What is this `if` for?

2023-11-27 22:59 UTC, paolafer commented on antea/scripts/process_mc_petit_FBK.py
> +    chargeof the event in each the plane and the minimum time. It also computes
Fix typos: chargeof --> charge of; in each the plane --> in each plane.

2023-11-28 07:26 UTC, NereaSalor commented on antea/scripts/process_mc_petit_FBK.py
> +    chargeof the event in each the plane and the minimum time. It also computes
done!

2023-11-28 07:27 UTC, NereaSalor commented on antea/scripts/process_mc_petit_FBK.py
> +            if n < 390: # To change the TOFPET plane
That's true. I changed the function and I didn't realize that know it is not necessary. Fixed it!

2023-11-28 09:34 UTC, paolafer commented
As a general comment, the functions used in the script should be placed outside the script, so that they can be used in other parts of the code. Try to find which folder should contain them and give them an adequate name.

2023-11-28 10:30 UTC, paolafer commented on antea/scripts/process_mc_petit_FBK.py
> +        print(f'Number of events = {len(events)}')
Why do you print again the total number of events in the file N times? It seems useless to me.

2023-11-28 10:33 UTC, paolafer commented on antea/scripts/process_mc_petit_FBK.py
> +        print('creating charge dataFrames')
These printouts can be useful in debugging, but I think they can be removed in the official code.

2023-11-28 10:34 UTC, paolafer commented on antea/scripts/process_mc_petit_FBK.py
> +    print(n_evts, n_bunches)
Same as below.

2023-11-28 10:35 UTC, paolafer commented on antea/scripts/process_mc_petit_FBK.py
> +            max_or0.append(or_0)
If you save the original charge, shouldn't you apply the fluctuation and the threshold also to it?

2023-11-29 09:58 UTC, paolafer requested changes

2023-11-29 09:58 UTC, paolafer commented on antea/reco/petit_reco_functions.py
> +    """
In the description I would specify that this function is to be used with the FBK sensors numbered in a specific way (100... 163, 200... 263 etc.).

2023-11-29 09:58 UTC, paolafer commented on antea/scripts/process_mc_petit_FBK.py
> -                print(f'TOF dataframe has no minimum time in plane 0 for event {evt}')
The prints in the exceptions are fine, because they do give useful information when someone uses the script.

2023-11-29 10:36 UTC, paolafer commented
Excellent job, Nerea! 
Now, before approving and merging the PR, I would like that you re-organized the commits, grouping those that are similar in the same commit and changing some comments to more specific ones, to make the history clearer. You can do it in magit with an interactive rebase; I can show you how to do it, if you're not familiar with that!

2023-11-29 17:08 UTC, paolafer approved these changes
Great job writing an example of how to use the FBK simulations! I approve it!

2023-11-29 17:08 UTC, merged